### ISSUE TITLE
How well does it work?

### ISSUE THREAD

**Issue by Its-Kenta** [ketronix-dev/linux-zen#1]
I saw your message on Solus forum and I appreciate your work. I think Solus really needs this.

I wanted to ask before I go ahead attempt to install it is that are there any known bugs or problems when running this kernel on Solus?

And if possible, what is the installation procedure for this?

Thank you!

**Comment by ketronix-dev** [comment]
Of the known bugs, the kernel did not boot on my old laptop in legacy boot.

How to install? You download all the files of a particular release, and install. If you want to be error-proof, install the kernel first, and then the headers.

**Comment by Its-Kenta** [comment]
Would you be able to post any installation instructions by any chance please?

**Comment by ketronix-dev** [comment]
In the releases section of the repository there are READY packages) You can install them with your package manager) Simply by entering the path to the packages.

**Comment by Its-Kenta** [comment]
Do any commands have to be run after installing the eopkg or it’s plug&play where the install deals with it all? (E.g. update grub and whatnot)

**Comment by ketronix-dev** [comment]
Well the package manager should do this by default. If it doesn't:

`sudo clr-boot-manager list-kernels`

A list of installed kernels will come up, you copy the name of the right one, and execute:

`sudo clr-boot-manager set-kernel <kernel>`

And if you have a legacy boot - you might have problems at this stage.

**Comment by Its-Kenta** [comment]
Thank you! That worked well! Had to actually run those commands to get that kernel set.
