### ISSUE TITLE
v6.0.3-3 - Hangs on boot

### ISSUE THREAD

**Issue by Its-Kenta** [ketronix-dev/linux-zen#2]
After updating kernel to 6.0.3-3 my Solus just hangs on boot, even when trying to switch to older version of kernel...
Any chance I could get some help finding a way fixing this?

**Comment by ketronix-dev** [comment]
So when you switch to an older kernel, you still don't get the OS to boot? I had a similar experience. And I solved it by pressing F8 when booting, and got to the grub menu, and there I selected the right kernel to boot, and after successfully booting I deleted the non-working kernel.

**Comment by Its-Kenta** [comment]
I even tried switching to 5.15 on selection one and it still doesn’t boot me in…

**Comment by ketronix-dev** [comment]
Is the screen just black? Or is there something on the screen?

**Comment by Its-Kenta** [comment]
Simply black and nothing happens.

**Comment by ketronix-dev** [comment]
I suggest that you chroot into your system and remove the new kernel.

**Comment by Its-Kenta** [comment]
> I suggest that you chroot into your system and remove the new kernel.

That’s what I’ve been trying to do, removed it but it’s still causing this problem…

**Comment by ketronix-dev** [comment]
Did you select a kernel to boot after uninstalling?

**Comment by ketronix-dev** [comment]
And yes, try chrooting the last zen kernel release. I just checked, I have problems too. Although it wasn't yesterday yet... Anyway, everything works on the last release. I guess I won't try to chase the absolute novelty...

**Comment by Its-Kenta** [comment]
I’ve chrooted into my system, set the kernel but it still fails to boot. This update pretty much bricked my Solus so I have to reinstall…

**Comment by ketronix-dev** [comment]
I'm really sorry about what happened. From now on I will test more thoroughly.
